name: Publish Image to DockerHub
on:
  push:
    branches:
      - master
    paths:
      - "entrypoint.sh"
      - "pre.Dockerfile"
      - "Pipfile"
      - "Pipfile.lock"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Image to DockerHub
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker pull $BASE_NAME || true
          docker build --cache-from $BASE_NAME -t $BASE_NAME -f pre.Dockerfile .
          docker push $BASE_NAME
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BASE_NAME: ${{ github.repository }}
