name: Build Docker Image
on:
  push:
    paths:
      - "entrypoint.sh"
      - "pre.Dockerfile"
      - "Pipfile"
      - "Pipfile.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker Image with DockerHub
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker pull $BASE_NAME || true
          docker build --cache-from $BASE_NAME -t $BASE_NAME -f pre.Dockerfile .
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BASE_NAME: ${{ github.repository }}
